---
  - name: Run apt-get update
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: Install unzip & tools if req
    apt:
      name: "{{ item }}"
    with_items:
      - unzip

  - name: Download the Vault binary
    get_url:
      url: https://releases.hashicorp.com/vault/0.10.4/vault_0.10.4_linux_amd64.zip
      dest: /home/ubuntu

  - name: Unzip the Vault binary
    unarchive:
      src: /home/ubuntu/vault_0.10.4_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes

  - name: Create vault user
    user:
      name: vault

  - name: Create Directory structure for vault
    file:
      path: /etc/vault.d
      state: directory
      mode: 0755

  - name: Copy the vault config
    template:
      src: vault-server-config.hcl.j2
      dest: /etc/vault.d/vault_server.hcl

  - name: Place the server systemd script on the vault servers
    template:
      src: vault-systemctl.conf.j2
      dest: /etc/systemd/system/vault.service

  - name: Make sure a service is running
    systemd:
      state: started
      name: vault.service

  - name: enable service consul.service
    systemd:
      name: vault.service
      enabled: yes
